name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-docs-${{ hashFiles('**/pyproject.toml', '**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-docs-

      - name: Install package + docs extras
        run: |
          python -m pip install --upgrade pip
          # If you defined a 'docs' extra in setup.cfg (recommended):
          pip install -e ".[docs]" || pip install -e .
          # Fallback install of doc tools if the extra isn't defined:
          pip install "sphinx>=7" "furo" "myst-nb" "sphinx-autodoc-typehints" "sphinx-copybutton" -q || true

      - name: Build Sphinx
        run: sphinx-build -b html docs docs/_build/html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
